### PR TITLE
Logged out fixes

### LINKED ISSUE #346: Interface does not work when user is logged out
- [x] Fix crash on logout
- [x] Fix getHistogram access issues
- [x] Fix empty histograms
- [x] Fix ERR_INCOMPLETE_CHUNKED_ENCODING problem when getting the page from mongodb
- [ ] <del>Adopt datasets when logging in</del>

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Fixes UI oddities when users are logged out.

Fixes #346

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Doesn't seem to be working :(

When I fire it up, I see (as expected) a 401 error in the console (since I'm not logged in).

I do "create new project", which seems to work just fine. Then I select a data set to load (I tried both cars and gapminder) which results in an error. I get three messages in the console, all of them 401s to `POST /item/<id>/dataset/getHistograms`.

**Comment by alex-r-bigelow** [comment]
Thanks for the catch! It should be fixed now for both mongo datasets and flat files.

**Comment by ronichoudhury** [comment]
Still seeing a problem. Now if I start from scratch, select "start with a dataset", then select, say, cars, the data set appears to load, then immediately disappears, and I get these errors in the console:

````
jquery.js:9203 GET http://localhost:8080/api/v1/user/authentication 401 (Unauthorized)
d3.js:670 Error: <rect> attribute width: A negative value is not valid. ("-64")
d3.js:663 Error: <svg> attribute width: A negative value is not valid. ("-32")
````

(The first error is expected, since I'm not logged in.)

**Comment by alex-r-bigelow** [comment]
I know I've seen those errors while logged in, so I'm fairly confident that they're symptoms of a separate issue (relevant to #353?), but I've had trouble replicating them.

Are you getting this behavior with all the datasets, or just cars?

**Comment by ronichoudhury** [comment]
Seems to be all of them. One time it worked. A few other times, I get a fatal error message about "couldn't update the reference to a copy of the <name> dataset".

If you want you can swing by my desk and I'll give you a live demo of what I'm seeing.

**Comment by ronichoudhury** [comment]
Looks like the problems this PR was designed to fix, are fixed. LGTM!

**Pull request merged**
