### PR TITLE
Fixup pycandela initialization, validate pycandela docs

### PR DESCRIPTION
**Pull request by jeffbaumes**
To test, `cd candela/python/pycandela` then run `jupyter-notebook`. Then create a new notebook and copy and paste in any of the pycandela examples in the sphinx docs (note the docs have been updated on this branch).

There is still an issue with geo, geodots, and lineup, since those examples do not have a good default height and do not allow setting of height well. That can be addressed in another PR.

With this PR tested and merged, it will be time to push a new pycandela version to pip.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
The tests are failing due to something about too many regex groups, originating from the girder_client install. Not sure what to do about it.

**Comment by jeffbaumes** [comment]
Looks like we are hitting this error on Travis http://stackoverflow.com/questions/39829473/cryptography-assertionerror-sorry-but-this-version-only-supports-100-named-gro

**Comment by jeffbaumes** [comment]
Following to the GitHub issue from that link seems to suggest it's fixed but pip caches need to be removed. However it does not seem that we are caching python stuff - unless Travis is doing it automatically somehow.

**Comment by ronichoudhury** [comment]
I just created a virtualenv locally and repeated the failing pip command, and I get the same error :worried:

I don't know how pip caching works but I tried to defeat it with a virtualenv. Maybe @zachmullen has some insights?

**Comment by ronichoudhury** [comment]
Ah it's not a girder-client problem; it's in the "cryptography" module, which comes in (I think) via requests.

**Comment by ronichoudhury** [comment]
https://github.com/pyca/cryptography/issues/3187

This says the problem has been fixed but that we may need to delete any cached wheels.

**Comment by zachmullen** [comment]
See https://github.com/DigitalSlideArchive/large_image/pull/106/files/1e6333d75626f9bcffcb12ce6cad2900f1c94fb4..40d3f637ae1c6cbf154be2418a1b636fbac0d284

**Comment by ronichoudhury** [comment]
Thanks @zachmullen.

A more direct fix is to install `pycparser==2.14` in the .travis.yml file before the other pip commands. I'm preparing a PR for Candela along those lines now.

**Comment by jeffbaumes** [comment]
This might have *just* been fixed:

https://github.com/eliben/pycparser/issues/151#issuecomment-254551279

**Comment by ronichoudhury** [comment]
Once #452 is vetted and merged, we can rebase this branch on master and let the tests pass before merging.

**Comment by ronichoudhury** [comment]
Heh yep, so can we just restart the Travis builds for this branch and see if it works? Or is something still pinned somewhere to a bad version?

**Comment by jeffbaumes** [comment]
I restarted the builds to see what happens.

**Comment by ronichoudhury** [comment]
Woo hoo!

**Pull request merged**
