### PR TITLE
User prefs

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
This contains a lot of changes to the reference app, including saving user state (preferences and toolchains), as well as making panels more modular (in preparation for adding more).

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I was able to recreate an bug:
* Choose "start with data"
* Select a dataset
* Open mapping panel
* Change dataset
* At this point, the mapping does not display the data fields - it is empty

**Comment by jeffbaumes** [comment]
This LGTM. There are a few bugs here and there but I'd rather get this on master now.

**Comment by alex-r-bigelow** [comment]
Sorry, I was getting caught up on the ISIC stuff today. If this is time sensitive, I'm happy to switch and fix stuff before we merge, ... or we can merge now and patch later. Either is fine by me.

**Comment by jeffbaumes** [comment]
I'll clarify my "now" as meaning "this week" as opposed to leaving it open for a while. No rush.

**Comment by alex-r-bigelow** [comment]
I think I've fixed the bug where swapping in a new dataset failed to trigger the appropriate render callbacks.

I'm going to start a separate branch for the more drastic changes we've discussed—I think this is as close as we'll get to something merge-able in the short term.

**Comment by jeffbaumes** [comment]
I verified that this bug is gone - LGTM.

**Pull request merged**
