### PR TITLE
Add metadata option to UpSet

### PR DESCRIPTION
**Pull request by jeffbaumes**
Style is a little off in Resonant Lab for the metadata selection, but otherwise this seems to work pretty well.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Example usage on Simpson's dataset with Age as metadata:

screen shot 2016-05-18 at 2 29 45 pm

**Comment by curtislisle** [comment]
Awesome!  Thanks!  This is a great feature for supporting drill down of individual data elements in UpSet!

**Comment by curtislisle** [comment]
Can we merge PR #242 on Candela soon or should it stay separate?  I'd like this in the ABCC deliverable and it increases UpSet's drill down capability.

**Comment by ronichoudhury** [comment]
More or less LGTM - @jeffbaumes if you think this is ok to merge, please go ahead and do so.

@curtislisle, the other option is to include this in the VM provisioning by commit hash (unless you want to refer to `master` in the provisioning script specifically).

**Pull request merged**
