### PR TITLE
Ansible cleanup

### PR DESCRIPTION
**Pull request by ronichoudhury**
- Use girder role from ansible galaxy
- Split playbook up into multiple taskbooks
- Move ansible stuff per-box-type into own directory
- Get rid of unsupported and unused xenial playbook

Thanks for the help @danlamanna

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Minus 2.2k lines! 🔪  Have the Resonant Lab deploy instructions changed or should I be able to follow what's in the current Readme to test?

**Comment by ronichoudhury** [comment]
I think the README is still valid - I strove to only change the internals of the playbooks themselves.

**Comment by ronichoudhury** [comment]
@jeffbaumes could you review this branch?

**Comment by ronichoudhury** [comment]
@jeffbaumes, could you try one more time?

**Comment by ronichoudhury** [comment]
FYI, the test failure is a Python style failure that has been fixed upstream already, so it should not hold this back from being merged if it's ok otherwise.

**Comment by ronichoudhury** [comment]
@jeffbaumes take another look please.

**Pull request merged**
