### PR TITLE
fix(build): Fixes broken build by ensuring new vega-canvas is not depended on

### LINKED ISSUE #527: Build breaking, likely due to some vega changes
See https://github.com/vega/vega-canvas/issues/1

### PR DESCRIPTION
**Pull request by jeffbaumes**
Fixes #527 

@ronichoudhury PTAL

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Also, Jeff authorized me to merge this in his stead -- doing so... now.

**Comment by jbeezley** [comment]
This isn't working for me as is for some reason.  Starting from a new directory and a bare `package.json`, when I run `npm install candela` I get:

```
$ npm ls vega
npm@1.0.0 /home/jbeezley/tmp/npm
└─┬ candela@0.18.1
  ├── vega@3.0.10 
  └─┬ vega-tooltip@0.4.4
    └── vega@3.0.10  deduped
```

```
$ node --version
v7.10.0
$ npm --version
5.6.0
```

Any ideas?

**Comment by jeffbaumes** [comment]
I believe the issue is that some candela tests are failing so it was not auto-published to npm by CI. The following should pull in the right versions (but does not have `dist` stuff so in general won't work).

```
npm i git+https://github.com/Kitware/candela
```

I think we need to get a candela release out. Ideas @ronichoudhury ?

**Comment by jbeezley** [comment]
Oh right.  I didn't even check if a new release was out.

**Pull request merged**
