### PR TITLE
Add box plot

### PR DESCRIPTION
**Pull request by jeffbaumes**

### CODE REVIEW

**Comment by ronichoudhury** [comment]
The code looks good. Could you add a demo app to demonstrate how it works?

**Comment by jeffbaumes** [comment]
I've added a very basic example app that includes a box plot. Ready for final review.

**Comment by jeffbaumes** [comment]
@ronichoudhury did you perhaps give me a LGTM on the wrong branch, #39? Your last comment looks out of place there. Regardless, let me know here if LGTY.

**Comment by ronichoudhury** [comment]
Yes I did. This LGTM.

**Pull request merged**
