### PR TITLE
Add fields option to input sets from any categorical field

### LINKED ISSUE #115: Let UpSet view work with non-boolean fields
Instead of assuming 0/1 fields, generate sets from any field by creating a series of sets named "field_name value" for each value found in the field.

### PR DESCRIPTION
**Pull request by jeffbaumes**
Fixes #115

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Can you explain exactly what this does? I am not too clear on it even after reading the diff and the issue it solves.

**Comment by jeffbaumes** [comment]
Certainly. UpSet only works on binary columns, i.e. columns with a literal "0" or "1" in every row indicating set membership. Any field in the `sets` option will be interpreted this way. Since most data is not arranged like that, I enable preprocessing of arbitrary categorical fields with the `fields` option. Each field specified in this list will first be preprocessed into a collection of 0/1 columns that are passed to UpSet.

For example, suppose the data table is:

| id | f1 | f2 |
| :-- | :-- | :-- |
| n1 | 1 | x |
| n2 | 0 | x |
| n3 | 0 | y |

You could create an UpSet visualization with the following options:

```js
new UpSet({
  data: data,
  id: 'id',
  sets: ['f1'],
  fields: ['f2']
});
```

This would preprocess the `f2` field into `f2 x` and `f2 y` sets as follows and make them available to UpSet:

| id | f1 | f2 x | f2 y |
| :-- | :-- | :-- | :-- |
| n1 | 1 | 1 | 0 |
| n2 | 0 | 1 | 0 |
| n3 | 0 | 0 | 1 |

You can also play with it in the reference app to see how these things work. I'll put docs like this into the UpSet component docs.

**Comment by jeffbaumes** [comment]
I updated the docs, ready for re-review.

**Comment by ronichoudhury** [comment]
Ah ok, makes total sense :-D.

LGTM!

**Pull request merged**
