### PR TITLE
Changing UpSet to be smarter about finding binary sets

### LINKED ISSUE #212: Make "sets" input of UpSet smarter
Take certain strings like "yes", "true" as inclusion values.

### PR DESCRIPTION
**Pull request by jeffbaumes**
Fixes #212.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
@curtislisle you had mentioned making the binary sets smarter - do these added cases suffice or are there some other ways binary fields appear in your data?

**Comment by ronichoudhury** [comment]
This looks good but can you update the documentation to explain that capitalization for the alternate terms doesn't matter?

More generally, I wonder if we can have a mode where you pass in a predicate function, and the result of running data through that function yields the 1/0 value used by UpSet?

**Comment by jeffbaumes** [comment]
@ronichoudhury I changed the docs to mention that strings are case insensitive, so this is ready for re-review.

Functors returning true or false could be added at some point, but right now I think we should focus on the bare serializable API. One concern is that we will need a different testing harness if we are going to support things like function arguments, and I'd like to keep the API as simple as possible for now.

**Comment by ronichoudhury** [comment]
You are right about serializability. Simplicity over generality at the current moment is the right way to go. It might make sense as an icebox issue to allow someone to specify what the binary values in their particular data set are (i.e. they could choose "si" == `true` and "non" == `false` if they are at KEU).

In any case, LGTM.

**Pull request merged**
