### PR TITLE
Fix breakages from girder-client v2.0

### PR DESCRIPTION
**Pull request by zachmullen**
Also remove usage of a private symbol in favor of a public one.

@jeffbaumes PTAL

### CODE REVIEW

**Comment by zachmullen** [comment]
Environment variable GIRDER_API_KEY is blank. Cannot upload images.

I'm assuming this is because I'm making this PR from a fork.

**Comment by ronichoudhury** [comment]
Yeah I think so. I'll create a remote to track your branch just to allow this test to run.

**Comment by zachmullen** [comment]
It makes sense, otherwise any old adversary could make a PR that just prints the value from your travis script.

Thanks!

**Comment by ronichoudhury** [comment]
Hey, look, it builds! https://travis-ci.org/Kitware/candela/builds/166774970

**Comment by ronichoudhury** [comment]
@zachmullen I added you as a collaborator so you should be able to push the button.

**Comment by ronichoudhury** [comment]
Thanks @zachmullen!

**Pull request merged**
