### PR TITLE
Remove ES6 example code and validate JS code examples

### LINKED ISSUE #401: Test and fix webpack and python doc examples
In particular, the webpack imports should be quoted.

### PR DESCRIPTION
**Pull request by jeffbaumes**
Fixes #401. Waiting for better CDN of candela so that we can replace links with ones that will point to the latest candela.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Since we now have a recent candela on npm, we can change sphinx and examples to point to `//unpkg.com/candela`.

The JS examples are now standalone and have been manually tested by copy/pasting into separate index.html files and viewed in-browser.

Ready for review.

**Comment by ronichoudhury** [comment]
The PR build failed because girder-client got a 400 error while uploading test images. I've restarted the build, but all the tests did pass.

**Comment by jeffbaumes** [comment]
Yes please do, because I don't know what you would want changed :)

**Comment by ronichoudhury** [comment]
@jeffbaumes PTAL at  e55cd5887587fc41a271a30201dc42676f7d4b08 and let me know if that looks ok. If yes, I'll do the rest of the examples as well.

**Comment by jeffbaumes** [comment]
Looks great, go for it.

**Comment by ronichoudhury** [comment]
@jeffbaumes I changed the rest of the examples. Let me know if it looks good and then I'll approve the PR.

**Comment by jeffbaumes** [comment]
Looks great, thanks! Your changes LGTM

**Comment by jeffbaumes** [comment]
Caught one more indent style fix in the getting started section.

**Comment by ronichoudhury** [comment]
Ah, thanks! I had meant to fix that stretch of example code but forgot.

**Pull request merged**
