### PR TITLE
Ansible provisioning infrastructure

### LINKED ISSUE #144: "Prepare Girder" script
I think we need a more comprehensive version of the [populateGirder](https://github.com/Kitware/candela/blob/master/app/resonant-reference-app/examples/populateGirder.py) script that also creates the anonymous user, sets up the necessary collection and subfolders, in addition to uploading the example data sets. This would make it easier to get going with a fresh build of Girder and Resonant Laboratory, and prevent some errors that pop up when you're *not* set up quite right.

### LINKED ISSUE #201: Create a deployment solution for Resonant Laboratory

### PR DESCRIPTION
**Pull request by ronichoudhury**
This adds a `Vagrantfile` and associated Ansible provisioning materials.

@alex-r-bigelow, could you try this out? Just check out this branch, go to `app/resonant-laboratory`, and do `vagrant up`. Once that process finishes, you should be able to go to http://localhost:8080 and see the deployment instance of Resonant Laboratory.

- Closes #144 
- Closes #201

### CODE REVIEW

**Comment by alex-r-bigelow** [comment]
It seems to get to the Create Girder admin user task, and then crashes. I'll probe further and report ASAP.

**Comment by ronichoudhury** [comment]
Can you post the error message that step emanates? It's a big nasty
dict/json looking thing, usually in red on the console.

**Comment by alex-r-bigelow** [comment]
Yup. Here it is (slightly cleaned up):

```json
{
  "changed": false,
  "failed": true,
  "invocation": {
    "module_args": {
      "apiRoot": null,
      "assetstore": null,
      "blacklist": null,
      "delete": null,
      "dryrun": null,
      "get": null,
      "host": null,
      "password": null,
      "plugins": null,
      "port": "8080",
      "post": null,
      "put": null,
      "scheme": null,
      "state": "present",
      "token": null,
      "user": "{'firstName': 'Admin', 'admin': True, 'lastName': 'User', 'login': 'admin', 'password': 'adminadmin', 'email': 'admin@example.com'}",
      "username": null
    },
    "module_name": "girder"
  },
  "msg": "<type 'exceptions.TypeError'>: user() takes at least 3 arguments (2 given)\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_SLt5hD/ansible_module_girder.py\", line 842, in main\n    gcm(module)\n  File \"/tmp/ansible_SLt5hD/ansible_module_girder.py\", line 520, in __call__\n    self.__process(method)\n  File \"/tmp/ansible_SLt5hD/ansible_module_girder.py\", line 548, in __process\n    ret = getattr(self, method)(*args, **kwargs)\nTypeError: user() takes at least 3 arguments (2 given)\n"
}
```

And the stack trace:
```
<type 'exceptions.TypeError'>: user() takes at least 3 arguments (2 given)

Traceback (most recent call last):
  File "/tmp/ansible_SLt5hD/ansible_module_girder.py", line 842, in main
    gcm(module)
  File "/tmp/ansible_SLt5hD/ansible_module_girder.py", line 520, in __call__
    self.__process(method)
  File "/tmp/ansible_SLt5hD/ansible_module_girder.py", line 548, in __process
    ret = getattr(self, method)(*args, **kwargs)
TypeError: user() takes at least 3 arguments (2 given)
```

**Comment by ronichoudhury** [comment]
Well, people generally seem to have been complaining that Ansible 2.1 breaks their workflows. So for now @alex-r-bigelow could you try downgrading to Ansible 2.0 and see if this works? In the meantime I'll work with Chris K. and see if we can figure out the fix for 2.1 and beyond.

**Comment by alex-r-bigelow** [comment]
LGTM. :+1:

**Comment by jeffbaumes** [comment]
Works for me too. This is very nice! @ronichoudhury could you add the instructions to RL's readme, including the version of Ansible that is known to work (it worked for me with `pip install -I ansible=2.0.2.0`)?

**Comment by ronichoudhury** [comment]
@jeffbaumes, will do. I didn't realize that Ansible is installable via pip! (My OS has it via the package manager.)

**Comment by alex-r-bigelow** [comment]
Yeah, I used
```bash
virtualenv env
source env/bin/activate
pip install ansible==2.0
```
to avoid conflicting with the (newer) system installation.

**Comment by ronichoudhury** [comment]
Thanks Alex. I'll mention this in the docs I'm adding now.

**Comment by ronichoudhury** [comment]
Docs updated! PTAL.

**Comment by alex-r-bigelow** [comment]
LGTM

**Pull request merged**
