### PR TITLE
[WIP] Match resonant website

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
See conversation in #403

### CODE REVIEW

**Comment by ronichoudhury** [comment]
I don't think Roboto Slab is right for the app, though it may just be because I am used to how it was before. The slab font is too heavy/bulky in, e.g., the matching panel. I think Roboto or even Roboto Condensed might work better (but of course I'd have to see it).

I may grab Steve Jordan tomorrow and get his opinion as well.

**Comment by alex-r-bigelow** [comment]
Do you mean the matching panel header, or the clickable pills inside? I thought the latter was one of the few places it *wasn't* too heavy. If you meant the header, that's actually Montserrat.

Both fonts have lighter weights available—If we want to match the Resonant website, we should use the same fonts as much as possible (changing the weight is usually a far less drastic change than dropping the slabs / going condensed).

**Comment by ronichoudhury** [comment]
Right, I meant inside the pills. I like the Montserrat caps in the window titles.

I actually don't think we need to make it an explicit goal to match the fonts in the Resonant website. If we do, that's ok, but the fonts need to serve their purpose within the app first and foremost.

**Comment by jeffbaumes** [comment]
Another option that I'll throw out there is that we can change the fonts on the Resonant website :) The main Girder client and various RTD are two others areas that would benefit from style normalization.

**Comment by ronichoudhury** [comment]
I'll take the bold position that our attempts to figure out typefaces for
Resonant Lab should not become a larger discussion about fonts on our other
websites at the current time :-P

**Comment by alex-r-bigelow** [comment]
In that light, it might be worth waiting for Kitware to implement some kind of branding style guide (I think @superlib mentioned something about revamping the main page—maybe all sites should conform to whatever styles are put in place there?)

**Comment by jeffbaumes** [comment]
Sorry for further devolving the conversation :) I agree with @ronichoudhury: make the app look good - if there are matches with the current Resonant website that's great but not required. I just wanted to add that the Resonant website did not have an in-depth style discussion so should not be considered gold-standard.

I like the energy around making RL look awesome, but for now let's pick a "good enough" and  we can always continue iterating later.

**Comment by ronichoudhury** [comment]
I'm planning to sit down with Steve later today, so we'll try to figure out
a combo that works generally. When overarching style guides come in some
day, we can reconsider RL as well.

**Comment by ronichoudhury** [comment]
Closing in favor of #403

**Pull request closed without merging**
