### PR TITLE
Integrate vcharts

### PR DESCRIPTION
**Pull request by ronichoudhury**
This PR "dissolves" vcharts more fully into Candela, in particular by redistributing many of the vcharts specs into dedicated Candela components.

@jeffbaumes can you take an overall look to make sure things look right? In particular, let me know if I got the option specifiers right.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Marking WIP for now because I want to include semistandard linting for the vcharts code. Stand by for unWIPing.

**Comment by ronichoudhury** [comment]
Well, that was easy. The vcharts code was already semistandard-compliant. Thanks @jeffbaumes! :tada:

**Comment by jeffbaumes** [comment]
LGTM. Let the merging messiness begin. The options are not in the correct final form but we need to just bite the bullet and start merging these. You can go first. It may be best to assume you can break the reference app then my merges will fix it again.

**Comment by alex-r-bigelow** [comment]
Yeah, I wouldn't worry too much about the reference app for now. I'm having to do a pretty deep refactor to get user preferences, toolchains, and datasets syncing with Girder anyway... so we might as well wait until my PR to fix reference app problems (hopefully early next week).

**Comment by ronichoudhury** [comment]
Now that I've LGTMed the other pending PRs, I'll go ahead and merge this... stand by.

**Comment by ronichoudhury** [comment]
So, one of the merge conflicts was between ``Box`` (my importation of ``box.json`` into a Candela component) and ``BoxPlot`` (@jeffbaumes's importation of the same, albeit without moving the spec itself out of vcharts).

I'll go ahead and merge this now since I got an LGTM and we want to move ahead and merge the other pending PRs, but if this is a problem we can revisit it later, comparing the code from Jeff's boxplot PR and the code in this PR.

**Pull request merged**
