### PR TITLE
Filter makeover

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Convert the dataset interface to show histogram previews of the dataset, as well as a table view.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
Can you fix this linting error?

````
/home/travis/build/Kitware/candela/app/resonant-laboratory/general_purpose/binUtils.js
  6:31  error  Missing radix parameter
````

**Comment by ronichoudhury** [comment]
I'm not sure there's a reasonable way to do the usual code review on this branch. If the application works as expected then I'd say it's ok to merge but we can wait for @jeffbaumes to weigh in too.

**Comment by jeffbaumes** [comment]
Agree, let's merge and iterate from there. We saw it working yesterday.

**Comment by alex-r-bigelow** [comment]
@the linting error: dang it, I thought I'd caught them all... for some reason ESLint isn't flagging those in my editor.

I agree that code review will be tricky. Before I finally remove the [WIP], I'll add a comment referencing all the issues that this branch should address—in addition to poking and prodding the interface, that should at least give us a checklist of things to go through and validate / discuss.

**Comment by ronichoudhury** [comment]
:+1:

**Comment by alex-r-bigelow** [comment]
@ronichoudhury, quick question: I don't think we have support for flat json files yet. This isn't a big deal—it should probably be its own PR—but for the sake of this one, I think I should:
- temporarily remove the example json files, or
- temporarily force them all to upload as mongo database collections in the upload script

Thoughts?

**Comment by ronichoudhury** [comment]
Spoke to Alex IRL - we decided to make the flat json files into Mongo DB items for now (until we figure out exactly what to do with them).

**Comment by alex-r-bigelow** [comment]
As promised, here's the list of issues that this PR addressed along the way:
- [ ] #278
- [ ] #265
- [ ] #251
- [ ] #219
- [ ] #204
- [ ] #203 (fixed for flat files; if a database changes, we still have no way of knowing)
- [ ] #170

**Comment by ronichoudhury** [comment]
The push CI test has a weird failure that isn't connected to anything on this branch, so LGTM! :tada: :tada: :tada:

**Pull request merged**
