### PR TITLE
Upload script fix

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Fix minor issues with populateGirder.py and dataset identification

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@jeffbaumes, you  may be able to test this PR more readily than me, since you use a GridFS assetstore.

**Comment by alex-r-bigelow** [comment]
I did switch my girder instance to GridFS and everything seems to work, but for verification purposes I agree that @jeffbaumes will probably need to test this one.

**Comment by ronichoudhury** [comment]
@jeffbaumes ping

**Comment by jeffbaumes** [comment]
I'm trying to try this now, but ran into a separate https://github.com/OpenGeoScience/girder_db_items issue that @manthey and I are working to resolve first which is making the script fail.

**Comment by jeffbaumes** [comment]
I verified this works with no filesystem assetstore now. LGTM. @alex-r-bigelow you can still do the honors if you'd like to press the green button.

**Comment by jeffbaumes** [comment]
I'll go ahead and press the green button :)

**Pull request merged**
