### PR TITLE
Only make use of extraParameters when it's a JSON string

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
database_assetstore sends non-JSON `"limit=1"` as `extraParameters` while importing database collections (this was causing `populateGirder.py` to crash). Any `extraParameters` payload is perfectly valid; our adapter should simply revert to default behavior when it doesn't recognize it.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
I disagree just a little bit: if we send a non-JSON string by mistake, this code path is supposed to raise an error to let us know. On the other hand, `database_assetstore` accepts both JSON extraParamters and a urlencoded variety. Is there some way we can shift the use case that's breaking this code path to simply use JSON instead? That would be a smaller fix that would maintain `semantic_assetstore_adapter`'s error reporting capabilities.

**Comment by alex-r-bigelow** [comment]
No, there really isn't anywhere else we can fix this problem—our `populateGirder` script needs to hit `database_assetstore`'s `import` endpoint, and that in turn issues a call to `download` (I think to probe table/collection headers?) with the non-JSON `extraParameters`. So we'd have to make `database_assetstore` conform to the JSON-only `extraParameters` to shift this case.

**Comment by ronichoudhury** [comment]
If we ask nicely, @manthey may be able to help us out ;)

**Comment by alex-r-bigelow** [comment]
Closing because @manthey is awesome.

**Pull request closed without merging**
