### PR TITLE
Image testing

### PR DESCRIPTION
**Pull request by ronichoudhury**
This adds infrastructure for performing image-based testing for various components.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
First I got an error saying `babel-node` is not found, so I performed:

```
npm install --save-dev babel-cli
```

After that I am getting farther but am now getting a lot of errors like this:

```
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/jeff/code/candela/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jeff/code/candela/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at /Users/jeff/code/candela/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/jeff/code/candela/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:413:34)
/Users/jeff/code/candela/src/candela/components/Box/test/box.image.js:1
(function (exports, require, module, __filename, __dirname) { import imageTest from '../../../util/imageTest';
                                                              ^^^^^^
```

**Comment by ronichoudhury** [comment]
Ah yeah, I actually fixed this in a downstream PR.

I can cherry-pick the commit to fix this onto this branch, stand by...

**Comment by ronichoudhury** [comment]
I fixed it - try again please.

**Comment by jeffbaumes** [comment]
Alright! Working now. I am getting failed image tests because my tests render with a transparent background instead of white. See e.g.:

bar-test
bar-test

bar-diff
bar-diff

**Comment by jeffbaumes** [comment]
The infrastructure LGTM, so this is good to merge. We can sort out rendering differences among platforms in Travis and other later PRs

**Pull request merged**
