### PR TITLE
Cleaner output from testing command

### PR DESCRIPTION
**Pull request by ronichoudhury**
This adds a command line filter to the NPM test script (along with some testing configuration changes) to capture and reformat the output in such a way that ``faucet`` is better able to process and pretty print the results.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I cannot see a difference compared to the `master` or `reorg` branches (maybe because we are not using phantom yet?). But LGTM regardless - I'm assuming it will help in that case.

**Comment by ronichoudhury** [comment]
Hm. You may see a difference when a test fails...

All this does is extract the pure tap output from Phantom, then run that through faucet.

**Comment by ronichoudhury** [comment]
I added another variation of ``npm test`` that doesn't process the output at all (as a fallback in case something weird happens).

I'm assuming the LGTM still stands.

**Comment by ronichoudhury** [comment]
Thanks! LGTM.

**Comment by jeffbaumes** [comment]
Raw test output task looks good.

**Pull request merged**
