### PR TITLE
Fix girder build

### PR DESCRIPTION
**Pull request by jeffbaumes**
Turns out my previous PR didn't work :) This fixes up a few things and make the plugin work a bit more like the osumo plugin by serving a directory, which lets us split out the index.html file.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@alex-r-bigelow can you take a look at this?

**Comment by jeffbaumes** [comment]
Forgot this was a dependency of #100 - it got merged just now. @alex-r-bigelow please check out this functionality regardless.

**Comment by alex-r-bigelow** [comment]
Yes, `grunt` by itself seems to work, but `grunt watch` doesn't seem to notice any changes (even if you force a webpack build while it's watching). I imagine it's not supposed to?

**Comment by jeffbaumes** [comment]
Right I did not work to get `grunt watch` working. Glad it is working for you.

**Pull request merged**
