### PR TITLE
Overhaul of examples infrastructure

### PR DESCRIPTION
**Pull request by ronichoudhury**
Each example is now its own application. Commonalities (such as testing a component in the same way with a set of options) have been abstracted into functions. A new build rule `npm run build:examples` has been implemented using an independent webpack config, since building the examples takes about a minute (compared to ~10s to build Candela itself).

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@jeffbaumes PTAL.

**Comment by jeffbaumes** [comment]
Suggestion: change npm command for showing examples from demo to examples.

**Comment by ronichoudhury** [comment]
@jeffbaumes, I made the suggested change. Could you give me an official go-ahead please? :-D

**Comment by jeffbaumes** [comment]
Sure, LGTM!

**Comment by jeffbaumes** [comment]
LGTM

**Pull request merged**
