### PR TITLE
Add aggregation option to histogram

### LINKED ISSUE #35: Create aggregate by property for histogram
Instead of counting each record as 1, enable an optional field for summing up the bin value

### PR DESCRIPTION
**Pull request by jeffbaumes**
Fixes #35

### CODE REVIEW

**Comment by ronichoudhury** [comment]
LGTM.

Is there generally a way to write unit tests for this sort of behavior?

**Comment by alex-r-bigelow** [comment]
LGTM. Very cool!

**Comment by jeffbaumes** [comment]
@ronichoudhury Yes there are a few options. 1. we could do image testing, 2. we could do SVG rendering and ensure some elements (like rects) are the right size, 3. we could ensure that the produced Vega spec is what we expected. I think the third option would be easiest to implement.

**Comment by ronichoudhury** [comment]
Option 3 is closest to what I think of as "unit testing". Option 1 is probably the easier "image test" to perform. I'll look into adding both test types once the testing infrastructure is a bit more bulletproof.

**Pull request merged**
