### PR TITLE
Include babel-loader in all test configurations

### PR DESCRIPTION
**Pull request by waxlamp**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
What's the context of this change, what problem does it solve?

**Comment by waxlamp** [comment]
There's no evident problem that it solves; for some reason, without this loader the tests seem to build properly, but for completeness I wanted to include the loader rule.

**Comment by waxlamp** [comment]
@jeffbaumes could you take another look at this please (made the change I discussed with your yesterday, which caused your earlier approval to be dismissed).

**Comment by jeffbaumes** [comment]
Circle is complaining with:

```
TypeError: Class constructor ScatterPlot cannot be invoked without 'new' FAILED
```

Is there something different about the transpilation that is affecting this?

**Comment by waxlamp** [comment]
I rebased this branch on master to properly incorporate the build improvements there--and if this doesn't just work, I'm inclined to drop this PR.

**Comment by waxlamp** [comment]
@jeffbaumes, looks like the problem is fixed now.

**Pull request merged**
