### PR TITLE
Fixup image testing

### PR DESCRIPTION
**Pull request by jeffbaumes**
Make a few changes to make images render more consistently cross-machine.

Still needs new images and testing on Travis/Linux.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
I will provide new test images, which @jeffbaumes can then test out on his local development machine. Stand by.

**Comment by jeffbaumes** [comment]
I see that the tests are passing with low percent difference on Travis, which is not expected. Does the font aliasing CSS not work on Linux?

**Comment by ronichoudhury** [comment]
Well, it's still using the old reference images. I will look on S3 to see
just what's going on, and then I need to render/upload new reference images.

**Comment by ronichoudhury** [comment]
Oh I misunderstood what you meant by low percent difference. Yes this is
unexpected.

**Comment by ronichoudhury** [comment]
Yeah, it seems that Chrome on Linux simply ignores the
-webkit-font-smoothing CSS directive.

If I rebase out the webkit CSS commit, can we accept this PR to fix the
sizing issue, then decide what to do separately for getting tests to pass
on OSX?

**Comment by jeffbaumes** [comment]
Sounds like a good plan.

**Comment by ronichoudhury** [comment]
I excised the font-smoothing commit, so LGTMITIH.

**Comment by ronichoudhury** [comment]
@jeffbaumes could you merge this?

**Pull request merged**
