### PR TITLE
Add branch-based versioning of projects to help us sandbox better as we develop

### LINKED ISSUE #255: Store / filter items based on Resonant lab version numbers
We run into this problem a lot: a given dataset or project item won't work with whatever version of resonant lab is being used.

Two ideas:
- For broader deployment, we should store Resonant Lab version numbers as metadata in these items, so we can update old items' metadata if/when necessary. Users should never have to deal with file version issues (MS Office, anyone?)
- For internal development, we could instead store the current branch name as the version (or commit hash?) via some kind of `subprocess.check_output(["git", "status"])` voodoo, so that 1) we don't run into bugs that have nothing to do with the current version that we're working on, and 2) we don't accidentally corrupt dataset/project metadata that was supposed to be stable. In development mode, we'd hide any items in the interface that don't match the current branch

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Fix #255

Projects are hidden in menus if they were created on a different branch than the current one (all projects are still accessible by URL)

### CODE REVIEW

**Comment by ronichoudhury** [comment]
How much extra work would it be to *mark* matching projects with a green checkmark, etc., and non-matching ones with a red X, rather than simply hide all non-matching ones? I ask because I can imagine this causing the opposite problem to the one it solves - someone switches to a new topic branch and suddenly they can't see any projects, even ones that will work because the metadata schema isn't going to change on that topic.

**Comment by ronichoudhury** [comment]
Also, what happens if a user doesn't have `git` on their path (because, e.g., it isn't installed)?

**Comment by alex-r-bigelow** [comment]
It would be a little bit of work... actually, it would make sense to include a (tiny) project version compatibility indicator as part of the glyph redesign in #164. For now, to use an old project on a new branch, the URLs will still work for any project—they just won't show up in the menu.

For now, the "version" comes back as `master` if the branch is actually master, release, or if `git status` fails for whatever reason (including the case where git isn't installed). In the future, I'm imagining an actual number to come back in these three scenarios.

**Comment by ronichoudhury** [comment]
Handling of nonexistent `git` sounds good.

Alex and I just discussed in meatspace, and he'll put a crude stopgap version compatibility indicator into the project icons as part of this PR, then rework that as necessary as part of #164. When that's done I can review one more time (since the code as is looks good and I'm just concerned about unconditionally hiding non-matching projects).

**Comment by alex-r-bigelow** [comment]
Turns out this wasn't as tricky as I thought. Great idea!

**Comment by ronichoudhury** [comment]
Very nice!

Do you think it makes more sense to mark the non-conforming projects with a warning, or the conforming ones with a green OK sign? I would think green OK sign because that will be the thing that draws your eye, but since you're getting the most benefit out of this feature I'll defer to you. Just let me know so I can ok this branch.

**Comment by alex-r-bigelow** [comment]
Ideally, a deployed app shouldn't have to worry about displaying any version information (we'd want to do something more formal like @jeffbaumes proposed to gracefully handle forward/back conversion)—a deployment of `master` or `release` should never contain our weird branch projects in the first place. My thoughts are that this indicator adds clutter that we really only care about as we're developing it. So for now I think it's best to just show a warning when there's a potential version conflict.

**Comment by ronichoudhury** [comment]
Oh ok I see. You wouldn't want all projects showing up with the green indicator on master.

Sounds good! LGTM.

**Pull request merged**
